Blog qvscode compute node script
NCAR/NHUG pull request #35
Opened 2024-12-16 22:41 UTC by neumanbrett

Blog post on how to use the _qvscode_ script to launch VSCode on a Casper compute node.

2024-12-17 23:10 UTC, vanderwb requested changes

2024-12-17 23:10 UTC, vanderwb commented on docs/blog/posts/2024-12-16-vscode-compute.md
> +2. In VSCode, connect to a Casper login node using RemoteSSH as described [here](https://ncar-hpc-docs.readthedocs.io/en/latest/environment-and-software/vscode/#connecting-to-derecho-or-casper)
Add a step instructing the user to load `ncarenv/24.12` since it will end up in the newer stack.

2024-12-17 23:10 UTC, vanderwb commented on docs/blog/posts/2024-12-16-vscode-compute.md
> +It is likely that this will become a system alias that can be called directly instead of needing to provide a full path. In the meantime, you can make an alias for the command to call it more easily
Can cut this, assuming you intend to add to the stack before the blog post is published.

2024-12-19 17:49 UTC, neumanbrett commented on docs/blog/posts/2024-12-16-vscode-compute.md
> +The `qvscode` script will ignore any variables that are not set.  At a minimum, you will need to set *system*, *project*, *nodes*, *num_cpus*, and *walltime*.  If the path variable is empty then you
Providing no path means that VSCode doesn't set a 'workspace' to scan for extensions (mostly intellisense/language servers) and can improve performance. You can still navigate GLADE with the terminal.  A default path is set for the user prompt mode as $pwd but users can break this if they're using the .qvscode_settings file or if they manually enter no value for the path in prompt mode.  I will note this as a reason for setting an empty path variable in the request.

2025-01-08 19:29 UTC, negin513 commented on docs/blog/posts/2024-01-07-vscode-compute.md
> +A new VSCode window will launch on the compute node after user input or reading from the settings file.  The above procedure can be simplified by using a settings file as described in the [Settings M
@neumanbrett :
A very minor comment: Do you want to mention password and duo authentication here for clarity?

For example:
A new VSCode window will launch on the compute node after user entering password and completing Duo authentication, or reading from the settings file. The above procedure can be simplified by using a settings file as described in the [Settings Mode](https://github.com/NCAR/NHUG/pull/35/files/983a8818c1d2d10121ac796d0a6b14fbb249880c..4bb980849b90116b407e117966d6370d31d6a81c#settings-mode) section.

2025-01-08 19:32 UTC, negin513 commented on docs/blog/posts/2024-01-07-vscode-compute.md
> +  Step 6 will not prompt you for a project code if you have PBS_ACCOUNT defined.
This sentence is not appearing in the info box (one space missing probably). 

https://nhug--35.org.readthedocs.build/en/35/blog/launch-vscode-on-casper-compute-nodes/#procedure

2025-01-08 19:38 UTC, negin513 approved these changes
@neumanbrett Thank you so much for the fantastic blog post and utility! The updates look great, and the improvements have made the post even clearer.

I’ve added two minor comments for your consideration. Overall, this looks excellent to me, and you’re welcome to merge it whenever you’re ready.

2025-01-08 21:35 UTC, merged